### ISSUE TITLE
Help with site

### ISSUE THREAD

**Issue by angunapuh** [Ryyn-Sd/rayyansaidi.com#1]
I'm working on my site, http://angunapuh.github.io. You seem to know a lot of JS since this folder has almost 100% javascript. You also said "Let me know about any projects that I should do" and I have one. Can you help with my site? @Ryyn-Sd?

**Comment by angunapuh** [comment]
I can share my folder with you if you want

**Comment by angunapuh** [comment]
https://github.com/angunapuh/angunapuh.github.io

**Comment by Ryyn-Sd** [comment]
K. I'll help u, but I used gatsby on this project

**Comment by angunapuh** [comment]
@Ryyn-Sd I'm still new to coding so I want something simple. I just want to learn the basics of JS and how it helps with a website. I know the basics like variables, functions, loops, if statements, etc. but I don't know how to integrate that and make it work with a website. I also want to start from scratch because I want to learn how to code a website from the ground up. Thanks for the help!

**Comment by Ryyn-Sd** [comment]
It seems like u have done some work already on it though! Do u mind if @nathanchu helps out?

**Comment by angunapuh** [comment]
Sure, I'll invite @nathanchu to the folder also.

**Comment by Ryyn-Sd** [comment]
OK!

**Comment by angunapuh** [comment]
@Ryyn-Sd  I used a template from start boostrap.

**Comment by Ryyn-Sd** [comment]
Oh. That's fine

**Comment by Ryyn-Sd** [comment]
1 sec

**Comment by Ryyn-Sd** [comment]
K. I'm back. Do u want to use Gatsby or Create-react-app or just a static website? Those are the things are the languages that I'm familiar with

**Comment by angunapuh** [comment]
I don't know what those are, I'm new to coding though so whatever is the simplest.

**Comment by Ryyn-Sd** [comment]
Oh. Static is just plain HTML, CSS, and JS. React is something created by facebook that they use, and it's open source, and it's kinda like an HTML and JavaScript hybrid. Gatsby is almost the same as React, but you can use several pages, and it's faster.

**Comment by nathanchu** [comment]
@angunapuh Static is simplest.

**Comment by angunapuh** [comment]
Ok then I'll do static.

**Comment by Ryyn-Sd** [comment]
I have to go. I'll come back around 6

**Comment by Ryyn-Sd** [comment]
Make that 7, or not even today

**Comment by nathanchu** [comment]
@angunapuh What exactly do you want? A redesign or to learn javascript, css, and html?

**Comment by angunapuh** [comment]
Ideally both, but I'm more focused on learning how to start a website from scratch than a redesign.

**Comment by Ryyn-Sd** [comment]
Oh. Interesting

**Comment by Ryyn-Sd** [comment]
I talked about it a little on my [website](https://rayyansaidi.com/) so u get some free advertising and so does github :)

**Comment by angunapuh** [comment]
I've been working on my html, css, and js at w3schools and I've created a new branch, called `new`, to start coding my website from scratch with. I have invited you to the repository at https://github.com/angunapuh/angunapuh.github.io/invitations.

**Comment by angunapuh** [comment]
Is there any way I can get github pages to deploy the `new` branch somewhere else (like `new.angunapuh.github.io` or `angunapuh.github.io/new`)?

**Comment by nathanchu** [comment]
Not with github pages but maybe netlify or vercel for the deployment. I prefer vercel.

**Comment by Ryyn-Sd** [comment]
Ya I have no idea what netlify is. That's why I used vercel for rayyansaidi.com

**Comment by angunapuh** [comment]
@Ryyn-Sd I've learned some javascript from w3schools, so I understand it more. Can you explain to me what gatsby and react is?

**Comment by Ryyn-Sd** [comment]
React is like a hybrid of HTML and JavaScript; and Gatsby is React, but you can use multiple pages and it's faster.

**Comment by Ryyn-Sd** [comment]
Sorry, but I decided not to do this project becuase I am going to remove the suggestions on my website.

**Comment by Ryyn-Sd** [comment]
However, if you want, you can look at my website’s code, the react docs, the Gatsby docs, or any other source to code your website
